## Step 1: Data Loading and Initial Overview

In [11]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [12]:
df=pd.read_csv(r"C:\Users\HP\Downloads\ecommerce_retail_transactions_raw.csv")

In [13]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,UK,Delivered,5.0
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,U.K.,Delivered,3.0
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,2025-10-17,Home & Kitchen,Storage Organizer,1,106.25,0.0,net banking,Chicago,U.S.A,Delivered,4.0
12176,ORD011799,CUST02583,2024/01/22,Beauty,Sunscreen SPF50,1,24.76,15.0,Pay Pal,Mumbai,india,Delivered,5.0
12177,ORD006638,CUST02113,02-28-2024,Grocery,Olive Oil 1L,1,29.95,10.0,U.P.I,Melbourne,AU,Pending,NaN
12178,ORD002576,CUST00298,2025-06-01,Beauty,Hair Dryer,1,41.41,15.0,Credit_Card,Vancouver,CA,Delivered,NaN
12179,ORD007337,CUST00195,11-18-2024,Books,Self-Help Book,4,27.81,0.0,NetBanking,Mumbai,India,Delivered,4.0

In [5]:
df.head()

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
0,ORD011416,CUST00003,2026-04-03,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,UK,Delivered,5.0
1,ORD000974,CUST00269,10-15-2024,Books,Fiction Novel,1,34.24,5.0,NetBanking,Toronto,CA,Shipped,NaN
2,ORD000617,CUST02075,17 Jun 2024,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,DEBIT CARD,Brisbane,Australia,Shipped,NaN
3,ORD006437,CUST02109,16/10/2025,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,U.K.,Delivered,3.0
4,ORD000740,CUST00349,06 Apr 2026,Home & Kitchen,Non-Stick Pan,2,72.00,NaN,Credit_Card,Montreal,CA,Delivered,NaN

In [6]:
df.shape

(12180, 13)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12180 entries, 0 to 12179
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          12180 non-null  object
 1   Customer_ID       12180 non-null  object
 2   Order_Date        12180 non-null  object
 3   Product_Category  12180 non-null  object
 4   Product_Name      12180 non-null  object
 5   Quantity          12180 non-null  int64
 6   Unit_Price_USD    12180 non-null  float64
 7   Discount_Percent  11445 non-null  float64
 8   Payment_Method    12180 non-null  object
 9   Shipping_City     11678 non-null  object
 10  Country           12180 non-null  object
 11  Order_Status      12180 non-null  object
 12  Customer_Rating   6030 non-null   float64
dtypes: float64(3), int64(1), object(9)
memory usage: 1.2+ MB

In [17]:
df.describe(include="all")

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating
count,12180,12180,12180,12180,12180,12180.000000,12180.00000,12180.000000,12180,11678,12180,12180,6030.000000
unique,12000,3374,4229,8,46,NaN,NaN,NaN,20,22,24,5,NaN
top,ORD010283,CUST00063,09-07-2024,Home & Kitchen,Fiction Novel,NaN,NaN,NaN,paypal,Abu Dhabi,UAE,Delivered,NaN
freq,2,11,12,1568,405,NaN,NaN,NaN,709,881,609,6673,NaN
mean,NaN,NaN,NaN,NaN,NaN,2.019458,61.55069,6.858785,NaN,NaN,NaN,NaN,3.896186
std,NaN,NaN,NaN,NaN,NaN,1.234956,52.53839,7.117463,NaN,NaN,NaN,NaN,1.113482
min,NaN,NaN,NaN,NaN,NaN,-1.000000,3.01000,0.000000,NaN,NaN,NaN,NaN,1.000000
25%,NaN,NaN,NaN,NaN,NaN,1.000000,22.02000,0.000000,NaN,NaN,NaN,NaN,3.000000
50%,NaN,NaN,NaN,NaN,NaN,2.000000,42.76500,5.000000,NaN,NaN,NaN,NaN,4.000000
75%,NaN,NaN,NaN,NaN,NaN,3.000000,87.71250,10.000000,NaN,NaN,NaN,NaN,5.000000
max,NaN,NaN,NaN,NaN,NaN,5.000000,249.84000,25.000000,NaN,NaN,NaN,NaN,5.000000

In [11]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'Product_Category',
       'Product_Name', 'Quantity', 'Unit_Price_USD', 'Discount_Percent',
       'Payment_Method', 'Shipping_City', 'Country', 'Order_Status',
       'Customer_Rating'],
      dtype='object')

In [14]:
df.isnull().sum()

Order_ID               0
Customer_ID            0
Order_Date             0
Product_Category       0
Product_Name           0
Quantity               0
Unit_Price_USD         0
Discount_Percent     735
Payment_Method         0
Shipping_City        502
Country                0
Order_Status           0
Customer_Rating     6150
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(180)

## Step 2: Data Pre-Processing

In [22]:
# Handle missing values

df['Discount_Percent'] = df['Discount_Percent'].fillna(0)

df['Shipping_City'] = df['Shipping_City'].fillna('Unknown')

df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].median())

# Check missing values again
df.isnull().sum()

Order_ID            0
Customer_ID         0
Order_Date          0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price_USD      0
Discount_Percent    0
Payment_Method      0
Shipping_City       0
Country             0
Order_Status        0
Customer_Rating     0
Shipping_City       0
dtype: int64

In [23]:
df=df.drop_duplicates()

In [24]:
df.duplicated().sum()

np.int64(0)

In [34]:
# Step 1: Parse the mixed date formats into datetime objects
df["Order_Date"] = pd.to_datetime(df["Order_Date"], format="mixed")

# Step 2: Format the dates into dd-mm-yy (e.g., '31-12-25')
df["Order_Date"] = df["Order_Date"].dt.strftime("%d-%m-%y")

In [29]:
df["Order_Date"].dtype

dtype('O')

In [31]:
# View first 10 converted values
print(df["Order_Date"].head(10))

# View last 10 converted values
print(df["Order_Date"].tail(10))

0    03-04-26
1    15-10-24
2    17-06-24
3    16-10-25
4    06-04-26
5    09-11-24
6    21-03-26
7    07-10-24
8    19-08-25
9    14-07-25
Name: Order_Date, dtype: object
12170    14-08-24
12171    21-10-24
12172    10-01-24
12173    04-07-25
12174    08-02-24
12175    17-10-25
12176    22-01-24
12177    28-02-24
12178    01-06-25
12179    18-11-24
Name: Order_Date, dtype: object

In [35]:
# 2. Standardize Payment_Method
payment_mapping = {
    "paypal": "PayPal",
    "PayPal": "PayPal",
    "Pay Pal": "PayPal",
    "net banking": "Net Banking",
    "Net Banking": "Net Banking",
    "NetBanking": "Net Banking",
    "UPI": "UPI",
    "U.P.I": "UPI",
    "upi": "UPI",
    "DEBIT CARD": "Debit Card",
    "debit card": "Debit Card",
    "Debit Card": "Debit Card",
    "CREDIT CARD": "Credit Card",
    "credit card": "Credit Card",
    "Credit Card": "Credit Card",
    "Credit_Card": "Credit Card",
    "COD": "Cash on Delivery",
    "cod": "Cash on Delivery",
    "Cash on Delivery": "Cash on Delivery",
    "cash on delivery": "Cash on Delivery",
}
df["Payment_Method"] = df["Payment_Method"].map(payment_mapping)

In [37]:
# View first 10 converted values
print(df["Payment_Method"].head(10))

# View last 10 converted values
print(df["Payment_Method"].tail(10))

0         Net Banking
1         Net Banking
2          Debit Card
3    Cash on Delivery
4         Credit Card
5         Net Banking
6                 UPI
7    Cash on Delivery
8         Net Banking
9              PayPal
Name: Payment_Method, dtype: object
12170         PayPal
12171    Credit Card
12172         PayPal
12173     Debit Card
12174    Credit Card
12175    Net Banking
12176         PayPal
12177            UPI
12178    Credit Card
12179    Net Banking
Name: Payment_Method, dtype: object

In [39]:
# 3. Standardize Country
country_mapping = {
    "UK": "United Kingdom",
    "U.K.": "United Kingdom",
    "uk": "United Kingdom",
    "United Kingdom": "United Kingdom",
    "USA": "United States",
    "U.S.A": "United States",
    "usa": "United States",
    "US": "United States",
    "United States": "United States",
    "CA": "Canada",
    "canada": "Canada",
    "Canada": "Canada",
    "DE": "Germany",
    "germany": "Germany",
    "Germany": "Germany",
    "IN": "India",
    "india": "India",
    "India": "India",
    "AU": "Australia",
    "australia": "Australia",
    "Australia": "Australia",
    "UAE": "United Arab Emirates",
    "U.A.E": "United Arab Emirates",
    "uae": "United Arab Emirates",
}
df["Country"] = df["Country"].map(country_mapping)

In [40]:
# View first 10 converted values
print(df["Country"].head(10))

# View last 10 converted values
print(df["Country"].tail(10))

0    United Kingdom
1            Canada
2         Australia
3    United Kingdom
4            Canada
5     United States
6         Australia
7     United States
8     United States
9           Germany
Name: Country, dtype: object
12170           Canada
12171    United States
12172          Germany
12173           Canada
12174        Australia
12175    United States
12176            India
12177        Australia
12178           Canada
12179            India
Name: Country, dtype: object

 ## Step 3:Handling Missing Data

In [41]:
#  Handle Missing Text Values in Shipping_City
df["Shipping_City"] = df["Shipping_City"].fillna("Unknown")

In [44]:
# View first 10 converted values
print(df["Shipping_City"].head(30))

# View last 10 converted values
print(df["Shipping_City"].tail(10))

0          London
1         Toronto
2        Brisbane
3      Birmingham
4        Montreal
5     Los Angeles
6        Brisbane
7        New York
8     Los Angeles
9          Munich
10      Melbourne
11       Montreal
12     Manchester
13       Montreal
14        Chicago
15          Delhi
16        Houston
17        Hamburg
18        Toronto
19         Munich
20       New York
21      Melbourne
22         Mumbai
23     Manchester
24          Dubai
25         Mumbai
26      Melbourne
27         Berlin
28        Chicago
29      Bengaluru
Name: Shipping_City, dtype: object
12170     Montreal
12171      Chicago
12172       Munich
12173      Toronto
12174       Sydney
12175      Chicago
12176       Mumbai
12177    Melbourne
12178    Vancouver
12179       Mumbai
Name: Shipping_City, dtype: object

In [45]:
#  Command to calculate and add the new column
df["Gross_Revenue_USD"] = df["Quantity"] * df["Unit_Price_USD"]

#  Commands to view the new column

# View the first 5 rows containing the relevant columns
print(df[["Order_ID", "Quantity", "Unit_Price_USD", "Gross_Revenue_USD"]].head())

# View summary statistics for Gross_Revenue_USD
print(df["Gross_Revenue_USD"].describe())

    Order_ID  Quantity  Unit_Price_USD  Gross_Revenue_USD
0  ORD011416         3            9.16              27.48
1  ORD000974         1           34.24              34.24
2  ORD000617         2          111.95             223.90
3  ORD006437         1           31.84              31.84
4  ORD000740         2           72.00             144.00
count    12000.000000
mean       124.542457
std        147.396745
min       -241.190000
25%         32.920000
50%         74.475000
75%        155.962500
max       1249.200000
Name: Gross_Revenue_USD, dtype: float64

In [47]:
# 3. Fill missing Discount_Percent values with 0 and calculate Discount_Amount_USD
df["Discount_Amount_USD"] = (
    df["Gross_Revenue_USD"] * (df["Discount_Percent"].fillna(0) / 100)
).round(2)

#  View the results
print(
    df[
        [
            "Order_ID",
            "Gross_Revenue_USD",
            "Discount_Percent",
            "Discount_Amount_USD",
        ]
    ].head(10)
)

    Order_ID  Gross_Revenue_USD  Discount_Percent  Discount_Amount_USD
0  ORD011416              27.48               5.0                 1.37
1  ORD000974              34.24               5.0                 1.71
2  ORD000617             223.90              15.0                33.58
3  ORD006437              31.84               0.0                 0.00
4  ORD000740             144.00               0.0                 0.00
5  ORD011216             125.28               0.0                 0.00
6  ORD002861              18.34               5.0                 0.92
7  ORD011407             112.47               0.0                 0.00
8  ORD005427              85.76               0.0                 0.00
9  ORD002304              20.77              10.0                 2.08

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12000 entries, 0 to 12179
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             12000 non-null  object
 1   Customer_ID          12000 non-null  object
 2   Order_Date           12000 non-null  object
 3   Product_Category     12000 non-null  object
 4   Product_Name         12000 non-null  object
 5   Quantity             12000 non-null  int64
 6   Unit_Price_USD       12000 non-null  float64
 7   Discount_Percent     12000 non-null  float64
 8   Payment_Method       12000 non-null  object
 9   Shipping_City        12000 non-null  object
 10  Country              12000 non-null  object
 11  Order_Status         12000 non-null  object
 12  Customer_Rating      12000 non-null  float64
 13  Shipping_City        12000 non-null  object
 14  Gross_Revenue_USD    12000 non-null  float64
 15  Discount_Amount_USD  12000 non-null  float64
dtypes: float64(5), int64(1), object(10)
memory usage: 1.6+ MB

## Adding new Columns

In [50]:
#  Calculate Net Revenue
df["Net_Revenue_USD"] = (
    df["Gross_Revenue_USD"] - df["Discount_Amount_USD"]
).round(2)

# View the result
print(
    df[
        [
            "Order_ID",
            "Gross_Revenue_USD",
            "Discount_Amount_USD",
            "Net_Revenue_USD",
        ]
    ].head(10)
)

    Order_ID  Gross_Revenue_USD  Discount_Amount_USD  Net_Revenue_USD
0  ORD011416              27.48                 1.37            26.11
1  ORD000974              34.24                 1.71            32.53
2  ORD000617             223.90                33.58           190.32
3  ORD006437              31.84                 0.00            31.84
4  ORD000740             144.00                 0.00           144.00
5  ORD011216             125.28                 0.00           125.28
6  ORD002861              18.34                 0.92            17.42
7  ORD011407             112.47                 0.00           112.47
8  ORD005427              85.76                 0.00            85.76
9  ORD002304              20.77                 2.08            18.69

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12000 entries, 0 to 12179
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             12000 non-null  object
 1   Customer_ID          12000 non-null  object
 2   Order_Date           12000 non-null  object
 3   Product_Category     12000 non-null  object
 4   Product_Name         12000 non-null  object
 5   Quantity             12000 non-null  int64
 6   Unit_Price_USD       12000 non-null  float64
 7   Discount_Percent     12000 non-null  float64
 8   Payment_Method       12000 non-null  object
 9   Shipping_City        12000 non-null  object
 10  Country              12000 non-null  object
 11  Order_Status         12000 non-null  object
 12  Customer_Rating      12000 non-null  float64
 13  Shipping_City        12000 non-null  object
 14  Gross_Revenue_USD    12000 non-null  float64
 15  Discount_Amount_USD  12000 non-null  float64
 16  Net_Revenue_USD      12000 non-null  float64
dtypes: float64(6), int64(1), object(10)
memory usage: 1.6+ MB

In [52]:
# Create Is_Discounted flag (returns True / False)
df["Is_Discounted"] = df["Discount_Percent"].fillna(0) > 0

# Or convert to 1 / 0 integer flag if preferred:
# df['Is_Discounted'] = (df['Discount_Percent'].fillna(0) > 0).astype(int)

# View sample results
print(df[["Order_ID", "Discount_Percent", "Is_Discounted"]].head(10))

    Order_ID  Discount_Percent  Is_Discounted
0  ORD011416               5.0           True
1  ORD000974               5.0           True
2  ORD000617              15.0           True
3  ORD006437               0.0          False
4  ORD000740               0.0          False
5  ORD011216               0.0          False
6  ORD002861               5.0           True
7  ORD011407               0.0          False
8  ORD005427               0.0          False
9  ORD002304              10.0           True

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12000 entries, 0 to 12179
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Order_ID             12000 non-null  object
 1   Customer_ID          12000 non-null  object
 2   Order_Date           12000 non-null  object
 3   Product_Category     12000 non-null  object
 4   Product_Name         12000 non-null  object
 5   Quantity             12000 non-null  int64
 6   Unit_Price_USD       12000 non-null  float64
 7   Discount_Percent     12000 non-null  float64
 8   Payment_Method       12000 non-null  object
 9   Shipping_City        12000 non-null  object
 10  Country              12000 non-null  object
 11  Order_Status         12000 non-null  object
 12  Customer_Rating      12000 non-null  float64
 13  Shipping_City        12000 non-null  object
 14  Gross_Revenue_USD    12000 non-null  float64
 15  Discount_Amount_USD  12000 non-null  float64
 16  Net_Revenue_USD      12000 non-null  float64
 17  Is_Discounted        12000 non-null  bool
dtypes: bool(1), float64(6), int64(1), object(10)
memory usage: 1.7+ MB

In [55]:
df

,Order_ID,Customer_ID,Order_Date,Product_Category,Product_Name,Quantity,Unit_Price_USD,Discount_Percent,Payment_Method,Shipping_City,Country,Order_Status,Customer_Rating,Shipping_City,Gross_Revenue_USD,Discount_Amount_USD,Net_Revenue_USD,Is_Discounted
0,ORD011416,CUST00003,04-03-26,Books,Self-Help Book,3,9.16,5.0,Net Banking,London,United Kingdom,Delivered,5.0,London,27.48,1.37,26.11,True
1,ORD000974,CUST00269,15-10-24,Books,Fiction Novel,1,34.24,5.0,Net Banking,Toronto,Canada,Shipped,4.0,Toronto,34.24,1.71,32.53,True
2,ORD000617,CUST02075,17-06-24,Home & Kitchen,Vacuum Cleaner,2,111.95,15.0,Debit Card,Brisbane,Australia,Shipped,4.0,Brisbane,223.90,33.58,190.32,True
3,ORD006437,CUST02109,16-10-25,Beauty,Hair Dryer,1,31.84,0.0,Cash on Delivery,Birmingham,United Kingdom,Delivered,3.0,Birmingham,31.84,0.00,31.84,False
4,ORD000740,CUST00349,04-06-26,Home & Kitchen,Non-Stick Pan,2,72.00,0.0,Credit Card,Montreal,Canada,Delivered,4.0,Montreal,144.00,0.00,144.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12175,ORD002515,CUST00071,17-10-25,Home & Kitchen,Storage Organizer,1,106.25,0.0,Net Banking,Chicago,United States,Delivered,4.0,Chicago,106.25,0.00,106.25,False
12176,ORD011799,CUST02583,22-01-24,Beauty,Sunscreen SPF50,1,24.76,15.0,PayPal,Mumbai,India,Delivered,5.0,Mumbai,24.76,3.71,21.05,True
12177,ORD006638,CUST02113,28-02-24,Grocery,Olive Oil 1L,1,29.95,10.0,UPI,Melbourne,Australia,Pending,4.0,Melbourne,29.95,3.00,26.95,True
12178,ORD002576,CUST00298,06-01-25,Beauty,Hair Dryer,1,41.41,15.0,Credit Card,Vancouver,Canada,Delivered,4.0,Vancouver,41.41,6.21,35.20,True
12179,ORD007337,CUST00195,18-11-24,Books,Self-Help Book,4,27.81,0.0,Net Banking,Mumbai,India,Delivered,4.0,Mumbai,111.24,0.00,111.24,False

 ## Step 4: Statistical Analysis

In [59]:
numeric_df = df.select_dtypes(include='number')

summary = pd.DataFrame({
    'Mean': numeric_df.mean(),
    'Median': numeric_df.median(),
    'Mode': numeric_df.mode().iloc[0],
    'Minimum': numeric_df.min(),
    'Maximum': numeric_df.max(),
    'Range': numeric_df.max() - numeric_df.min(),
    'Variance': numeric_df.var(),
    'Standard_Deviation': numeric_df.std()
})

summary

,Mean,Median,Mode,Minimum,Maximum,Range,Variance,Standard_Deviation
Quantity,2.018750,2.000,1.00,-1.00,5.00,6.00,1.521859,1.233636
Unit_Price_USD,61.524733,42.780,11.81,3.01,249.84,246.83,2751.746149,52.457089
Discount_Percent,6.870833,5.000,0.00,0.00,25.00,25.00,50.716709,7.121566
Customer_Rating,3.949833,4.000,4.00,1.00,5.00,4.00,0.615701,0.784666
Gross_Revenue_USD,124.542457,74.475,0.00,-241.19,1249.20,1490.39,21725.800299,147.396745
Discount_Amount_USD,8.506297,2.110,0.00,-37.39,242.42,279.81,272.875493,16.518943
Net_Revenue_USD,116.036161,69.015,0.00,-238.14,1249.20,1487.34,19181.586480,138.497605

 # Handling Outliers

In [17]:
Q1 = df['Unit_Price_USD'].quantile(0.25)
Q3 = df['Unit_Price_USD'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df['Unit_Price_USD'] < lower) |
    (df['Unit_Price_USD'] > upper)
]

print(outliers[['Product_Category', 'Product_Name', 'Unit_Price_USD']].head(20))

     Product_Category       Product_Name  Unit_Price_USD
22        Electronics       Gaming Mouse       186.25125
36        Electronics  Bluetooth Speaker       186.25125
50        Electronics             Webcam       186.25125
119       Electronics       Gaming Mouse       186.25125
134       Electronics         Power Bank       186.25125
297       Electronics         Smartwatch       186.25125
303       Electronics        USB-C Cable       186.25125
378       Electronics         Smartwatch       186.25125
465       Electronics         Smartwatch       186.25125
482       Electronics        USB-C Cable       186.25125
500       Electronics  Bluetooth Speaker       186.25125
659       Electronics         Smartwatch       186.25125
801       Electronics   Wireless Earbuds       185.29000
855       Electronics         Smartwatch       186.25125
1069      Electronics   Wireless Earbuds       186.25125
1141      Electronics             Webcam       186.25125
1156      Electronics  Bluetooth Speaker       186.25125
1163      Electronics         Power Bank       186.25125
1177      Electronics   Wireless Earbuds       186.25125
1190      Electronics       Laptop Stand       186.25125

In [18]:
Q1 = df['Unit_Price_USD'].quantile(0.25)
Q3 = df['Unit_Price_USD'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_mask = (
    (df['Unit_Price_USD'] < lower_bound) |
    (df['Unit_Price_USD'] > upper_bound)
)

print("Outliers before removal:", outlier_mask.sum())

df = df[~outlier_mask].copy()

print("Outliers after removal:", (
    (df['Unit_Price_USD'] < lower_bound) |
    (df['Unit_Price_USD'] > upper_bound)
).sum())

Outliers before removal: 198
Outliers after removal: 0